package connector

import (
	"context"
	_ "embed"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"go.mau.fi/util/random"

	"maunium.net/go/mautrix"
	"maunium.net/go/mautrix/bridgev2"
	"maunium.net/go/mautrix/bridgev2/database"
	"maunium.net/go/mautrix/bridgev2/networkid"
	"maunium.net/go/mautrix/event"
)

// A tiny real H.264 clip, so resolving to a video produces something that actually plays.
//
//go:embed resolvedsample.mp4
var resolvedSampleVideo []byte

// unresolvedMediaContent mirrors the marker mautrix-meta puts on unresolved Instagram cards
// (`UnresolvedMediaContent` in pkg/msgconv/igconv/xma.go). Keeping the shape and field names
// identical is the whole point: clients must not need to special-case dummybridge.
type unresolvedMediaContent struct {
	Kind string                     `json:"kind"`
	Base *event.MessageEventContent `json:"fi.mau.instagram.base_part,omitempty"`
}

// filterUnresolvedMediaContent mirrors the bridge's own filtering: only the fields a client needs
// to render the placeholder survive into the marker.
func filterUnresolvedMediaContent(content *event.MessageEventContent) *event.MessageEventContent {
	if content == nil {
		return nil
	}
	// Deliberately no Format, matching mautrix-meta exactly: the real marker carries
	// formatted_body without format, and the resolver re-derives it. Including it here would let
	// a client that wrongly depends on format pass against dummybridge and fail against Instagram.
	return &event.MessageEventContent{
		MsgType:       content.MsgType,
		Body:          content.Body,
		FormattedBody: content.FormattedBody,
		URL:           content.URL,
		Info:          content.Info,
		File:          content.File,
	}
}

// Behaviours the generated placeholder resolves with. The mode is encoded in the message ID
// rather than in the marker so that, like a real bridge, ResolveMedia decides what to do from
// server-side state and never trusts what the client echoed back.
const (
	unresolvedModeImage = "image"
	unresolvedModeVideo = "video"
	unresolvedModeFail  = "fail"
	unresolvedModeSlow  = "slow"
)

var unresolvedModes = []string{unresolvedModeImage, unresolvedModeVideo, unresolvedModeFail, unresolvedModeSlow}

const unresolvedMessageIDPrefix = "unresolved-"

// slowResolveDelay is long enough to see a loading state and try cancelling, short enough not to
// hit client or proxy timeouts.
const slowResolveDelay = 10 * time.Second

func unresolvedMessageID(mode string) networkid.MessageID {
	return networkid.MessageID(fmt.Sprintf("%s%s-%s", unresolvedMessageIDPrefix, mode, strings.ToLower(random.String(16))))
}

// unresolvedModeFromMessageID recovers the behaviour from the ID minted above. Returns "" for
// messages that were not generated by the unresolved-media command.
func unresolvedModeFromMessageID(id networkid.MessageID) string {
	rest, ok := strings.CutPrefix(string(id), unresolvedMessageIDPrefix)
	if !ok {
		return ""
	}
	mode, _, ok := strings.Cut(rest, "-")
	if !ok {
		return ""
	}
	return mode
}

var _ bridgev2.MediaResolvingNetworkAPI = (*DummyClient)(nil)

// ResolveMedia turns a placeholder generated by the unresolved-media command into real media.
//
// This mirrors the Instagram connector's contract so clients can be exercised end to end without
// Instagram: exactly one "provider lookup", a reupload, and an edit applied to the original event
// carrying com.beeper.dont_render_edited.
func (dc *DummyClient) ResolveMedia(
	ctx context.Context,
	portal *bridgev2.Portal,
	msg *database.Message,
	unresolvedMedia json.RawMessage,
) (*bridgev2.ResolvedMedia, error) {
	// Validate the echoed marker exactly as the real bridge does, so a client that fails to send
	// it back fails here too rather than silently working against the test bridge.
	var marker unresolvedMediaContent
	if err := json.Unmarshal(unresolvedMedia, &marker); err != nil {
		return nil, fmt.Errorf("failed to unmarshal unresolved media: %w", err)
	} else if marker.Base == nil {
		return nil, fmt.Errorf("unrecognized unresolved media content")
	}

	mode := unresolvedModeFromMessageID(msg.ID)
	if mode == "" {
		return nil, mautrix.MNotFound.WithMessage("Message isn't a resolvable dummy placeholder")
	}

	switch mode {
	case unresolvedModeFail:
		// A request-local failure: the card must stay intact and the account must stay connected.
		return nil, mautrix.MNotFound.WithMessage("Simulated resolve failure (dummy 'fail' mode)")
	case unresolvedModeSlow:
		select {
		case <-time.After(slowResolveDelay):
		case <-ctx.Done():
			// The caller gave up (client cancelled, or the request timed out).
			return nil, ctx.Err()
		}
	}

	intent := portal.Bridge.Bot

	var content *event.MessageEventContent
	switch mode {
	case unresolvedModeVideo, unresolvedModeSlow:
		// Resolving to a video is the interesting case: the edit changes msgtype, so clients have
		// to swap the whole message renderer rather than just reload an image.
		url, file, err := intent.UploadMedia(ctx, portal.MXID, resolvedSampleVideo, "resolved.mp4", "video/mp4")
		if err != nil {
			return nil, fmt.Errorf("failed to upload resolved video: %w", err)
		}
		content = &event.MessageEventContent{
			MsgType: event.MsgVideo,
			URL:     url,
			File:    file,
			Info: &event.FileInfo{
				MimeType: "video/mp4",
				Size:     len(resolvedSampleVideo),
				Width:    160,
				Height:   120,
				Duration: 2000,
			},
		}
	default:
		// A *different* cat than the placeholder, so it is obvious the media actually changed.
		catDesc, err := searchCat(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to search for resolved image: %w", err)
		}
		mediaMime, mediaData, err := getCat(ctx, catDesc.URL)
		if err != nil {
			return nil, fmt.Errorf("failed to fetch resolved image: %w", err)
		}
		url, file, err := intent.UploadMedia(ctx, portal.MXID, mediaData, "resolved"+extensionForMime(mediaMime), mediaMime)
		if err != nil {
			return nil, fmt.Errorf("failed to upload resolved image: %w", err)
		}
		content = &event.MessageEventContent{
			MsgType: event.MsgImage,
			URL:     url,
			File:    file,
			Info: &event.FileInfo{
				MimeType: mediaMime,
				Size:     len(mediaData),
				Width:    catDesc.Width,
				Height:   catDesc.Height,
			},
		}
	}

	// Keep the caption (and its trailing link) from the placeholder, and demote the old preview to
	// a thumbnail — both mirror what the Instagram connector does on resolve.
	content.Body = marker.Base.Body
	content.FormattedBody = marker.Base.FormattedBody
	if content.FormattedBody != "" {
		content.Format = event.FormatHTML
	}
	if content.Info != nil && marker.Base.MsgType == event.MsgImage {
		content.Info.ThumbnailURL = marker.Base.URL
		content.Info.ThumbnailFile = marker.Base.File
		content.Info.ThumbnailInfo = marker.Base.Info
	}

	return &bridgev2.ResolvedMedia{
		Edit: &bridgev2.ConvertedEditPart{
			Part:    msg,
			Type:    event.EventMessage,
			Content: content,
			// The new content deliberately carries no com.beeper.unresolved_media: its absence is
			// what tells clients the message is resolved.
			Extra: map[string]any{
				"external_url": fakeExternalURL(msg.ID),
			},
			TopLevelExtra: map[string]any{
				// This was a bridge-applied replacement, not a user edit.
				"com.beeper.dont_render_edited": true,
			},
		},
	}, nil
}

func extensionForMime(mime string) string {
	switch {
	case strings.Contains(mime, "png"):
		return ".png"
	case strings.Contains(mime, "gif"):
		return ".gif"
	default:
		return ".jpg"
	}
}

func fakeExternalURL(id networkid.MessageID) string {
	return fmt.Sprintf("https://www.instagram.com/reel/%s/", id)
}
