name: Build and Deploy

on:
  push:
  pull_request:
    branches: [ master ]

env:
  GO_VERSION: 1.19
  CI_REGISTRY_IMAGE: "${{ secrets.CI_REGISTRY }}/dummybridge"
  GHCR_REGISTRY: ghcr.io
  GHCR_REGISTRY_IMAGE: "ghcr.io/${{ github.repository }}"

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Beeper Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.CI_REGISTRY }}
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest
        run: |
          docker pull ${{ env.CI_REGISTRY_IMAGE }}:latest || true

      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          cache-from: ${{ env.CI_REGISTRY_IMAGE }}:latest
          file: Dockerfile
          tags: |
            ${{ env.CI_REGISTRY_IMAGE }}:${{ github.sha }}
            ${{ env.GHCR_REGISTRY_IMAGE }}:${{ github.sha }}
          push: true

  deploy-docker:
    runs-on: ubuntu-latest
    needs:
      - build-docker
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Login to Beeper Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.CI_REGISTRY }}
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag latest on Beeper Docker registry
        run: |
          docker pull ${{ env.CI_REGISTRY_IMAGE }}:${{ github.sha }}
          docker tag ${{ env.CI_REGISTRY_IMAGE }}:${{ github.sha }} ${{ env.CI_REGISTRY_IMAGE }}:latest
          docker push ${{ env.CI_REGISTRY_IMAGE }}:latest

      - name: Tag latest on ghcr
        run: |
          docker pull ${{ env.GHCR_REGISTRY_IMAGE }}:${{ github.sha }}
          docker tag ${{ env.GHCR_REGISTRY_IMAGE }}:${{ github.sha }} ${{ env.GHCR_REGISTRY_IMAGE }}:latest
          docker push ${{ env.GHCR_REGISTRY_IMAGE }}:latest

      - name: Run bridge CD tool
        env:
          CI_REGISTRY: "${{ secrets.CI_REGISTRY }}"
          BEEPER_DEV_ADMIN_API_URL: "${{ secrets.BEEPER_DEV_ADMIN_API_URL }}"
          BEEPER_STAGING_ADMIN_API_URL: "${{ secrets.BEEPER_STAGING_ADMIN_API_URL }}"
          BEEPER_PROD_ADMIN_API_URL: "${{ secrets.BEEPER_PROD_ADMIN_API_URL }}"
          BEEPER_DEV_ADMIN_NIGHTLY_PASS: "${{ secrets.BEEPER_DEV_ADMIN_NIGHTLY_PASS }}"
          BEEPER_STAGING_ADMIN_NIGHTLY_PASS: "${{ secrets.BEEPER_STAGING_ADMIN_NIGHTLY_PASS }}"
          BEEPER_PROD_ADMIN_NIGHTLY_PASS: "${{ secrets.BEEPER_PROD_ADMIN_NIGHTLY_PASS }}"
        run: |
          wget "https://gitlab.com/beeper/bridge-cd-tool/-/jobs/2886074151/artifacts/raw/bridge-cd-tool" \
            -O bridge-cd-tool && chmod +x bridge-cd-tool && ./bridge-cd-tool
