name: Build Docker

on:
  push:
  pull_request:
    branches: [main]

env:
  BEEPER_BRIDGE_TYPE: dummybridge
  CI_REGISTRY_IMAGE: "${{ secrets.CI_REGISTRY }}/bridge/dummybridgego"
  GHCR_REGISTRY: ghcr.io
  GHCR_REGISTRY_IMAGE: "ghcr.io/${{ github.repository }}/go"
  GHCR_REGISTRY_LOGINHELPER_IMAGE: "ghcr.io/${{ github.repository }}/loginhelper"

jobs:
  build-docker-dummybridge:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Beeper Docker registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.CI_REGISTRY }}
        username: ${{ secrets.CI_REGISTRY_USER }}
        password: ${{ secrets.CI_REGISTRY_PASSWORD }}

    - name: Login to ghcr
      uses: docker/login-action@v3
      with:
        registry: ${{ env.GHCR_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Build
      uses: docker/build-push-action@v6
      with:
#        cache-from: ${{ env.CI_REGISTRY_IMAGE }}:latest
        pull: true
        file: ./cmd/dummybridge/Dockerfile
        tags: |
          ${{ env.CI_REGISTRY_IMAGE }}:${{ github.sha }}
          ${{ env.GHCR_REGISTRY_IMAGE }}:${{ github.sha }}
        push: true

  build-docker-loginhelper:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ghcr
      uses: docker/login-action@v3
      with:
        registry: ${{ env.GHCR_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Build
      uses: docker/build-push-action@v6
      with:
        cache-from: ${{ env.GHCR_REGISTRY_LOGINHELPER_IMAGE }}/loginhelper:latest
        pull: true
        file: ./cmd/loginhelper/Dockerfile
        tags: |
          ${{ env.GHCR_REGISTRY_LOGINHELPER_IMAGE }}:${{ github.sha }}
          ${{ env.GHCR_REGISTRY_LOGINHELPER_IMAGE }}:latest
        push: true
